name: e2e-standalone-tests
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/e2e-standalone-tests.yml'
      - '**.py'
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        optuna-version: ['git+https://github.com/optuna/optuna.git']
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup Optuna ${{ matrix.optuna-version }}
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          python -m pip install --progress-bar off --upgrade ${{ matrix.optuna-version }}

      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off .
          python -m pip install --progress-bar off pytest-playwright==0.4.3  # next version is flaky

      - name: Build standalone_app
        working-directory: standalone_app
        run: |
          npm install
          npx vite build --outDir dist

      - name: Install the required browsers
        run: playwright install

      - name: Run e2e tests
        run: pytest e2e_tests/test_standalone
