name: Build Python distributions and publish to PyPI

on:
  release:
    types:
      - published

jobs:
  pypi:
    name: Build and publish Python distributions to TestPyPI and PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: gh release download $(jq --raw-output .tag_name "$GITHUB_EVENT_PATH") -p '*.whl' -p '*.tar.gz' -D ./dist
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
