name: typescript-checks
on:
  pull_request:
    paths:
      - '.github/workflows/typescript-tests.yml'
      - '.eslintrc.js'
      - '**.ts'
      - '**.tsx'
      - 'optuna_dashboard/package.json'
      - 'optuna_dashboard/package-lock.json'
      - 'optuna_dashboard/tsconfig.json'
      - 'optuna_dashboard/webpack.config.js'
jobs:
  lint:
    name: Lint checking on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint

  build:
    name: JS build check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build bundle.js
        working-directory: optuna_dashboard
        run: |
          npm install
          npm run build:dev
          npm run build:prd

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Run jest
        working-directory: optuna_dashboard
        run: |
          npm install
          npm run test

  test-tslib:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: x64

      - name: Generate test asset
        working-directory: tslib/storage/test/
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          pip install --progress-bar off optuna
          python generate_assets.py

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
      - name: Build test
        run: make tslib
      - name: Run tslib test
        working-directory: tslib/storage
        run: |
          npm run test
