name: typescript-checks
on:
  pull_request:
    paths:
      - '.github/workflows/typescript-tests.yml'
      - '.eslintrc.js'
      - 'biome.json'
      - '**.ts'
      - '**.tsx'
      - 'optuna_dashboard/package.json'
      - 'optuna_dashboard/package-lock.json'
      - 'optuna_dashboard/tsconfig.json'
      - 'optuna_dashboard/webpack.config.js'
jobs:
  lint:
    name: Lint checking on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - run: npm install
      - run: npm run lint

  type-check:
    name: Type checking on optuna-dashboard
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Setup tslib
        run: make tslib
      
      - name: Type Check
        working-directory: optuna_dashboard
        run: |
          npm install
          npm run type-check

  build:
    name: JS build check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build bundle.js
        working-directory: optuna_dashboard
        run: |
          npm install
          npm run build:dev
          npm run build:prd

  test-tslib:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: x64

      - name: Generate test asset for storage
        working-directory: tslib/storage/test/
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          pip install --progress-bar off optuna
          python generate_assets.py
      
      - name: Generate test asset for react
        working-directory: tslib/react/test/
        run: |
          python generate_assets.py

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build test
        run: make tslib

      - name: Run tslib test for storage
        working-directory: tslib/storage
        run: |
          npm run test
      
      - name: Run tslib test for react
        working-directory: tslib/react
        run: |
          npm run test
